apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: "worker-${WORKER2_UUID}"
  labels:
    qemu.xfix.org/uuid: "${WORKER2_UUID}"
    kubernetes.a7d.dev/machine.group: batch1
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-01
  vmid: 421
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      mac: "0e:68:df:5f:8d:26"
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - ${CLUSTER}
    - management-cluster
    - ${QEMU_WORKER_SKU}
  options:
    ostype: "l26"
    bios: "seabios"
    machine: "pc-i440fx-8.0"
    smbios1: "uuid=${WORKER2_UUID},sku=${QEMU_WORKER_SKU_B64},family=${QEMU_FAMILY_B64},base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
