apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/dex
patches:
- path: dex-k8s-authenticator-values.yaml
- path: dex-secret-dex-config.yaml
- path: dex-secret-dex-github-secret.yaml
- path: dex-secret-dex-k8s-authenticator-credentials.yaml
- path: dex-values.yaml
