apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talos-cloud-controller-manager
  namespace: kube-system
spec:
  releaseName: talos-cloud-controller-manager
  chart:
    spec:
      chart: talos-cloud-controller-manager
      sourceRef:
        kind: HelmRepository
        name: talos-cloud-controller-manager
        namespace: kube-system
      version: ">=v0.2.0 < v0.3.0"
  interval: 60m
  install:
    remediation:
      retries: 3
