apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:Mqr6rKcvDivFLDZeNdmAagTN4JMkRF+Xfo2psq+iHNrx4J35h6TMyBfofCCh3UbQFssGsgqFENMua6kTHeMEpjJYYPF8tyTJ/ZXOgYdvYOalsRdWWZY3l+cW7gZ76I3I2UGV8AoGZ7pZX/H6Lvx08mOwEm/UT1Wh6Jol5v9wVjgOIeElVohuhC5N3jg9XU/5oycKAnYFnmawgDrjs+fj9lygnnkYIj9slX2OsX3cBWQsUaqwiWj7qdkgL+jYVAth8Hvel2BIpcm5EYq0QN2BqMVBCPBR3jMLFK4fHTFK6baIYhoiJZ3/L1qTA6RQRj5H+vioOexn9fVp6lfY,iv:0FA+Db2dy+Wn2GlYBpM4BOYNDqN832BI/GEO8dh+aDw=,tag:LODG9dmAkXTYkZlsq4+1fA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: cluster-room101-a7d-mc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xslhlhf7u3xy5pvrz4anpc0cltmuxgm8whm9686dpssqg86vv52s47wyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U0swUnZCcEhqT0ViUWRY
            eU5wLzJUa0lza0Z0V3JaZHYzc3VoREd4Q1RjCjU1YWwrY3VRdTEwWHNsMkVLR0Uy
            WlE0cUhPV0h2ZGQvSEZiK3dqVVpMNkUKLS0tIDZscWNWUDdSS2hxY0YwRld0R1pw
            UUx0RG5vdk9zVldpcjVOc3lhd3FlUDAKK5CoRF7N6xLUT3vv7VvEHrXFLrNXTJBq
            E5sJG1FJBZ6H12bjN2qP4An+EuQ5r+ZzeJnn6FfDcLRgAxn6cMHeZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T20:30:22Z"
    mac: ENC[AES256_GCM,data:uKblgi8OnD4M+omTEZ5Gu2r/BOSpnzfbb6mxvgC+OmWRFZLo3a53MaP95ZjsSh/PfiQrfIEociRqe8mNODSPskk4L3C028hfT+S4s6YAjRSxMB8i+EjpeA1SdfDdzgP1TqxYHThoFyciQhFFEMMejd0ZyuqOsxzwHqqwu1fIGS8=,iv:r+x0+dcMH3GpDEDfZ7JdTd7enqp5galUo7no7Jc5Gmg=,tag:hOzOKnBRyYGU/zs3M8H1OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
