apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex-k8s-authenticator
  namespace: dex
spec:
  releaseName: dex-k8s-authenticator
  chart:
    spec:
      chart: dex-k8s-authenticator
      sourceRef:
        kind: HelmRepository
        name: sagikazarmark
      version: ">=0.0.2 <0.1.0"
  interval: 10m0s
  install:
    disableWait: true
  values:
    config:
      clusters:
        - name: ${CLUSTER}
          short_description: ${CLUSTER}
          description: "${DEX_AUTHENTICATOR_DESCRIPTION}"
          issuer: https://${DEX_SUBDOMAIN}.${CLUSTER_FQDN}
          client_id: ${STATIC_CLIENT_ID}
          client_secret: ${STATIC_CLIENT_SECRET}
          redirect_uri: https://${DEX_AUTHENTICATOR_SUBDOMAIN}.${CLUSTER_FQDN}/callback
          k8s_master_uri: https://${APISERVER_SUBDOMAIN}.${CLUSTER_FQDN}:${APISERVER_PORT}
    envFrom:
      - secretRef:
          name: dex-k8s-authenticator-credentials
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: ${DEX_AUTHENTICATOR_SUBDOMAIN}.${CLUSTER_FQDN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dex-k8s-authenticator-tls
          hosts:
            - ${DEX_AUTHENTICATOR_SUBDOMAIN}.${CLUSTER_FQDN}
