apiVersion: v1
data: {}
kind: Secret
metadata:
    name: dex-config
    namespace: dex
---
apiVersion: v1
data: {}
kind: Secret
metadata:
    name: dex-github-secret
    namespace: dex
---
apiVersion: v1
data: {}
kind: Secret
metadata:
    name: dex-k8s-authenticator-credentials
    namespace: dex
