apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
  interval: 60m
  storageNamespace: external-dns
  targetNamespace: external-dns
  values:
    extraArgs:
      annotation-filter: "external-dns.alpha.kubernetes.io/exclude notin (true)"
      cloudflare-dns-records-per-page: 100
      cloudflare-record-comment: "provisioned by external-dns"
      crd-source-apiversion: "externaldns.k8s.io/v1alpha1"
      crd-source-kind: "DNSEndpoint"
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cf-auth
            key: cloudflare_api_token
    policy: sync
    provider:
      name: cloudflare
    sources:
      - crd
      - ingress
