#
# apply CNI prereqs
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 10-cni-prereqs
  namespace: cluster-room101-a7d-mc
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/cni/prereqs
  prune: true
  wait: true
  suspend: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
---
#
# install CNI
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 11-cni
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 10-cni-prereqs
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/cni
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-mc
      target:
        kind: HelmRepository
        name: cilium
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-mc
        - op: add
          path: /spec/storageNamespace
          value: cilium
        - op: add
          path: /spec/targetNamespace
          value: cilium
        - op: replace
          path: /spec/values/k8sServiceHost
          value: k8s.room101-a7d-mc.lab.a7d.dev
      target:
        kind: HelmRelease
        name: cilium
  suspend: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
---
#
# apply CNI configs (BGP etc)
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 12-cni-configs
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 11-cni
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/clusters/room101-a7d-mc/cilium-configs
  prune: true
  wait: true
  suspend: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
