---
#
# install MC addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 30-addons
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 24-ccm
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/cluster-type/capi-cluster
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
      - kind: Secret
        name: cluster-vars-secret
        optional: false
  patches:
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: cert-manager/cert-manager
          value: 1.18.2
      target:
        kind: HelmRelease
        name: cert-manager
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: democratic-csi/democratic-csi
          value: 0.15.0
      target:
        kind: HelmRelease
        name: democratic-csi-nfs
    - patch: |
        - op: add
          path: /spec/values/txtOwnerId
          value: "room101a7dmc"
        - op: add
          path: /spec/values/sources
          value:
            - crd
            - ingress
        - op: add
          path: /spec/values/crd
          value:
            create: true
            apiversion: "externaldns.k8s.io/v1alpha1" # CHECKME
            kind: "DNSEndpoint"
        - op: replace
          path: /spec/chart/spec/version
          # renovate: kubernetes-sigs/external-dns
          value: 8.9.2
      target:
        kind: HelmRelease
        name: external-dns
    - patch: |
        - op: add
          path: /spec/values/controller/service/loadBalancerIP
          value: "${NGINX_SVC_IP}"
        - op: replace
          path: /spec/chart/spec/version
          # renovate: kubernetes/ingress-nginx
          value: 4.13.0
      target:
        kind: HelmRelease
        name: ingress-nginx
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: kyverno/kyverno
          value: 3.4.4
      target:
        kind: HelmRelease
        name: kyverno
---
#
# create configs which depend on controllers which were installed by the prior kustomization
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 31-addons-post-install
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 30-addons
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/config/post/room101-a7d-mc
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-admission-controller
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-background-controller
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
