---
#
# install MC addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 30-addons
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 24-ccm
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/cluster-type/capi-cluster
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  suspend: false
  patches:
    - patch: |
        - op: add
          path: /spec/values/controller/service/loadBalancerIP
          value: "${NGINX_SVC_IP}"
      target:
        kind: HelmRelease
        name: ingress-nginx
    - patch: |
        - op: add
          path: /spec/values/providerIpPrefixes
          value:
            - 172.25.100.0/27
      target:
        kind: HelmRelease
        name: kubelet-csr-approver
    - patch: |
        - op: add
          path: /spec/values/txtOwnerId
          value: "room101a7dmc"
        - op: add
          path: /spec/values/sources
          value:
            - crd
            - ingress
        - op: add
          path: /spec/values/crd
          value:
            create: true
            apiversion: "externaldns.k8s.io/v1alpha1" # CHECKME
            kind: "DNSEndpoint"
      target:
        kind: HelmRelease
        name: external-dns
---
#
# create configs which depend on controllers which were installed by the prior kustomization
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 31-addons-post-install
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 30-addons
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/config/post
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-admission-controller
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-background-controller
  suspend: false