#
# install MC-specific controllers
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 40-controllers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 31-addons-post-install
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/controllers/cluster-role/management-cluster
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
---
#
# install CAPI providers
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 41-controllers-capi-providers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 40-controllers
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/controllers/base/cluster-api-operator/capi-providers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  patches:
    - patch: |
        - op: add
          path: /spec
          value:
            # renovate: datasource=github-releases
            # repo=siderolabs/cluster-api-bootstrap-provider-talos
            version: v0.6.9
      target:
        kind: BootstrapProvider
        name: talos # https://github.com/siderolabs/cluster-api-bootstrap-provider-talos
    - patch: |
        - op: add
          path: /spec
          value:
            # renovate: datasource=github-releases
            # repo=siderolabs/cluster-api-control-plane-provider-talos
            version: v0.5.10
      target:
        kind: ControlPlaneProvider
        name: talos # https://github.com/siderolabs/cluster-api-control-plane-provider-talos
    - patch: |
        - op: add
          path: /spec
          value:
            # renovate: datasource=github-releases
            # repo=kubernetes-sigs/cluster-api
            version: v1.10.4
      target:
        kind: CoreProvider
        name: cluster-api # https://github.com/kubernetes-sigs/cluster-api
    - patch: |
        - op: add
          path: /spec/version
          # renovate: datasource=github-releases
          # repo=ionos-cloud/cluster-api-provider-proxmox
          value: v0.7.3
      target:
        kind: InfrastructureProvider
        name: proxmox # https://github.com/ionos-cloud/cluster-api-provider-proxmox
