---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 41-controllers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 40-controllers-pre-install
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/controllers/cluster-role/management-cluster
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  suspend: false
  patches:
    - patch: |
        - op: add
          path: /spec/endpoints/0
          value:
            dnsName: sidero-http.room101-a7d-mc.lab.a7d.dev
            recordTTL: 180
            recordType: A
            targets:
            - "${SIDERO_HTTP_IP}"
      target:
        kind: DNSEndpoint
        name: sidero
    - patch: |
        - op: add
          path: /spec/endpoints/1
          value:
            dnsName: sidero-siderolink.room101-a7d-mc.lab.a7d.dev
            recordTTL: 180
            recordType: A
            targets:
            - "${SIDERO_SIDEROLINK_IP}"
      target:
        kind: DNSEndpoint
        name: sidero
    - patch: |
        - op: add
          path: /spec/endpoints/2
          value:
            dnsName: sidero-tftp.room101-a7d-mc.lab.a7d.dev
            recordTTL: 180
            recordType: A
            targets:
            - "${SIDERO_TFTP_IP}"
      target:
        kind: DNSEndpoint
        name: sidero
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 43-controllers-capi-providers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 42-controllers-infrastructure-provider-prereqs
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/controllers/base/cluster-api-operator/capi-providers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  patches:
    - patch: |
        - op: add
          path: /spec
          value:
            # renovate: siderolabs/cluster-api-bootstrap-provider-talos
            version: v0.6.6
      target:
        kind: BootstrapProvider
        name: talos # https://github.com/siderolabs/cluster-api-bootstrap-provider-talos
    - patch: |
        - op: add
          path: /spec
          value:
            # renovate: siderolabs/cluster-api-control-plane-provider-talos
            version: v0.5.7
      target:
        kind: ControlPlaneProvider
        name: talos # https://github.com/siderolabs/cluster-api-control-plane-provider-talos
    - patch: |
        - op: add
          path: /spec
          value:
            # renovate: kubernetes-sigs/cluster-api
            version: v1.8.3
      target:
        kind: CoreProvider
        name: cluster-api # https://github.com/kubernetes-sigs/cluster-api
    - patch: |
        - op: add
          path: /spec/version
          # renovate: siderolabs/sidero
          value: v0.6.6
      target:
        kind: InfrastructureProvider
        name: sidero # https://github.com/siderolabs/sidero
