#
# apply all addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 70-apps
  namespace: cluster-room101-a7d-mc
spec:
  interval: 10m0s
  dependsOn:
    - name: 60-cluster-configs
      namespace: cluster-room101-a7d-mc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-mc
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
---
#
# apply config for addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 71-apps-configs
  namespace: cluster-room101-a7d-mc
spec:
  interval: 10m0s
  dependsOn:
    - name: 70-apps
      namespace: cluster-room101-a7d-mc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-mc/post-setup
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false