#
# pre-setup for addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 70-apps-pre-setup
  namespace: cluster-room101-a7d-mc
spec:
  interval: 10m0s
  dependsOn:
    - name: 60-cluster-configs
      namespace: cluster-room101-a7d-mc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-mc/pre-setup
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
---
#
# install addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 71-apps
  namespace: cluster-room101-a7d-mc
spec:
  interval: 10m0s
  dependsOn:
    - name: 70-apps-pre-setup
      namespace: cluster-room101-a7d-mc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-mc
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  patches:
    #
    # pinniped-concierge
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: vmware/pinniped
          value: 2.4.20
      target:
        kind: HelmRelease
        name: pinniped-concierge
    #
    # pinniped-supervisor
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: vmware/pinniped
          value: 2.4.20
      target:
        kind: HelmRelease
        name: pinniped-supervisor
    #
    # oauth2-proxy-a7d-dev
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: oauth2-proxy/oauth2-proxy
          value: 6.24.2
      target:
        kind: HelmRelease
        name: oauth2-proxy-a7d-dev
    #
    # oauth2-proxy-analbeard-com
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: oauth2-proxy/oauth2-proxy
          value: 6.24.2
      target:
        kind: HelmRelease
        name: oauth2-proxy-analbeard-com
---
#
# post-setup for addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 72-apps-post-setup
  namespace: cluster-room101-a7d-mc
spec:
  interval: 10m0s
  dependsOn:
    - name: 71-apps
      namespace: cluster-room101-a7d-mc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-mc/post-setup
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
