apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 95-cluster-room101-a7d-prod1
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: ./flux/clusters/room101-a7d-prod1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
