apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${CLUSTER}-workers
  namespace: ${CLUSTER_NAMESPACE}
spec:
  clusterName: ${CLUSTER}
  replicas: ${WORKER_COUNT}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: ${CLUSTER}-workers
      clusterName: ${CLUSTER}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: ${CLUSTER}-workers
      version: ${K8S_VERSION}
