apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: changeme
  namespace: default
spec:
  allowedNodes: []
  controlPlaneEndpoint:
    host: 0.0.0.0
    port: 6443
  dnsServers: []
  ipv4Config:
    addresses: []
    gateway: 0.0.0.0
    prefix: 24