apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: ${CLUSTER}
  namespace: ${CLUSTER_NAMESPACE}
  labels:
    flux-target: proxmoxcluster
spec:
  allowedNodes: []
  controlPlaneEndpoint:
    host: ${APISERVER_SUBDOMAIN}-${CLUSTER_FQDN}
    port: ${APISERVER_PORT}
  dnsServers:
    - ${NAMESERVER_1}
    - ${NAMESERVER_2}
  ipv4Config:
    addresses:
      - ${CLUSTER_NODE_NET_RANGE}
    gateway: ${CLUSTER_NODE_NET_GATEWAY}
    prefix: ${CLUSTER_NODE_SUBNET_CIDR}
