apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: changeme
  namespace: default
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_VERSION}
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: ProxmoxMachineTemplate
    name: ${CLUSTER}-cp
  replicas: ${CONTROLPLANE_COUNT}
  version: ${K8S_VERSION}
