apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ${CLUSTER}-cp
  namespace: ${CLUSTER_NAMESPACE}
  labels:
    flux-target: taloscontrolplane
spec:
  controlPlaneConfig:
    controlplane:
      configPatches: []
      generateType: controlplane
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: ${CLUSTER}-cp-${CP_MACHINE_SALT}
    namespace: ${CLUSTER_NAMESPACE}
  replicas: ${CONTROLPLANE_COUNT}
  version: ${K8S_VERSION}
