apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: ">=1.13.0 <1.14.0"
  interval: 10m0s
  values:
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
    cni:
      uninstall: false
    containerRuntime:
      integration: auto
    preflight:
      enabled: true

# TODO: cilium node-port support?
