apiVersion: config.supervisor.pinniped.dev/v1alpha1
kind: FederationDomain
metadata:
  name: ${PINNIPED_FEDERATION_DOMAIN}
spec:
  issuer: "https://${PINNIPED_SUPERVISOR_SUBDOMAIN}.${CLUSTER_FQDN}/${PINNIPED_FEDERATION_DOMAIN}"
  identityProviders:
    - displayName: Github
      objectRef:
        apiGroup: idp.supervisor.pinniped.dev
        kind: GitHubIdentityProvider
        name: github
  tls:
    secretName: ${PINNIPED_SUPERVISOR_SUBDOMAIN}.${CLUSTER_FQDN}-tls
