apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets-docker-io
  annotations:
    policies.kyverno.io/title: Add imagePullSecrets for docker.io images
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy adds an imagePullSecret to a Pod if the Pod is using an image from
      the docker.io registry.
spec:
  rules:
  - name: add-imagepullsecret-docker-io
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - <(image): "docker.io/*"
          imagePullSecrets:
          - name: docker-io-credentials
