apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno-helmrelease.yaml
  - kyverno-helmrepository.yaml
  - namespace-kyverno.yaml
  - policies/clusterpolicy-proxmox-operator-proxy-env-vars.yaml
