apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  labels:
    app: pinniped-concierge
  name: pinniped-concierge-config
  namespace: pinniped-concierge
spec:
  impersonationProxy:
    externalEndpoint: concierge.${CLUSTER_FQDN}
    mode: enabled
    service:
      type: ClusterIP
