apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pinniped-concierge

resources:
  - credentialissuer.yaml
  - ingress-impersonation-proxy.yaml
  - jwt-authenticator.yaml
  - poddisruptionbudget.yaml
