apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        version: 7.3.2
  interval: 1m0s
  values:
    annotationFilter: "external-dns.alpha.kubernetes.io/exclude notin (true)"
    cloudflare:
      proxied: false
      secretName: external-dns-cf-auth
    policy: sync
    provider: cloudflare
