apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 7.5.7 # https://github.com/bitnami/charts/issues/25967
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  values:
    annotationFilter: "external-dns.alpha.kubernetes.io/exclude notin (true)"
    cloudflare:
      proxied: false
      secretName: external-dns-cf-auth
    policy: sync
    provider: cloudflare
