apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUt4UUZlOVhBVFM3UnVVZ0xEbmNtMGd3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlNekV5TVRFeE56RXdNalphRncwek16RXlNRGd4TnpFdwpNalphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVJhOUdabEU4S2VRSVRlRG92VUpRUlNTYWFXVUErVGFKaWdQTWVjSnR1dWNCSkxLdkhCZ1psWWl1cTgKZDB1MzI0SWtvS1ZLRjZlbHhBMno1bmRLaXdBM28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTHBvSzA1MnVJR1Fick01UEhtMWRDYzVoTzAxTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDZG1KRmoKZ21KOS9qbFRUc3AvK3puN2FvdVpMOVpxWmRkM2ZhUHVRL2F5ZmdJaEFPNlg4RDhodnA2enMrMmJaZlpxU3ZGSQpWUExKVWovdFNLd1Mrcm1RM1pkNAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://k8s.room101-a7d-mc.lab.a7d.dev:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public