apiVersion: v1
kind: ConfigMap
metadata:
  name: democratic-csi-iscsi-values
  namespace: democratic-csi
data:
  values.yaml: |
    driver:
      config:
        instance_id: storage-k8s-mc-iscsi
        httpConnection:
          host: 172.25.100.3
        sshConnection:
          host: 172.25.100.3
        zfs:
          datasetParentName: storage/k8s/mc/iscsi/vols
        iscsi:
          targetPortal: "172.25.100.3:3260"
          nameSuffix: "-room101-a7d-mc"
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
