apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-vars-configmap.yaml
  - cluster-vars-secret.yaml
  - namespace-cluster-room101-a7d-mc.yaml
  - namespace-flux-system.yaml
  - secret-proxmox-provider-auth.yaml
  - sops-age-secret.yaml
