apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:oo49ndShF5/mPZec/NcaTABsj+/Q9xFSgqMUM7qHPuDB/s5qNuuCVNsZLySIEnzXkNqh9mkT12vfpqb06PgxqHxni+c4fWX3Mzw//zOHCQo+zioBUFZFbRk/SolUig24ACOInRQhzsfyQvlWrYm0JHaTQ6/FJZpT/9bQeecYM4rnKuIbAmr32AWBY8RCT6tCO1sUsObKhbTlf3QOIsXkaT6gY67npbCMsdWnSnvR4jTvOr/8hI79xjvhomWyMa+dtsqUbSDp/qYePhzZNpN5aCM5qzwgWWzp81ONFlaNHITgs8JMvqacy+gpE67dbatB+WNbqOjT+SPQCxiK4PIIzUi66hSv4IoQb9efgyV9BYEwpUtYR38CAflcl6GlmhOQxSZz264fAdDX/aR/8XhpM1gQ2nYLisP4nrt8Kk+B7XobDBmRijB8kFa4ZnKdSlCaqOnGuTLkIT5kt7NLdFvgVNyLWnOHyiKsLmWupBLas+dV4KDANGjhz3B+uWmwm2wFbQzzwrpMFEqsrUb5/L7yj2g7o8bIpHHhm5kK0X0GzmOEaF7q1eEVrmFWU8ZlYTLw+WON39HuFGCrHLe7S/1UIKFTH8UP4AhveFaG3sEbNbMAH5Wpi+KeuSyd+ZSWwimN7QTvN/Tk0+i+W9b4aR5tP0k44N/zUrrnGFadAjd33RaGA/V2y0DVTk0sk1o3arcUc7zsMFAVf5dyQ0ZEe6GmNzOYxb6ee1Xtu3hO+1C5hqGuKtjX9I54d4TAH6XnV2zmz313kX/iRUoZ3PEsfoNJpwUITxyJVrVi3ZrbH3HRXawP150LqU/ssr4zY4lmCdMqYsn/xf395MlUBipHPW/pJi0b2hBdh/zncoFN2h9s+bMR9CrJCP4QKY+w1kJCjAZ5vPNHsHvLQhAmFANc9Vvnw4+6ACaqS5CfaTczUVvLBg8Yhu8UP4On2/GcAqulw6etVt28U6sODiFv6FcAZQkMvAjTHKwJvGyCs6dzmm02K69SuF9xNx7HIlIRjCy8kH6VNziPwBFuUmoRr+9NE/DrIrIwTQs6C+II3y9gjvzlBvmQAAyi4zZxhcASWOK2/HzPStn+YpT30evon6uefAeNbveSkSZT0jda965s1dGlMh58Bh5opAHbJfJ2HFzckD5C0hMDztWAlKBPko2wctgRtflGXmFa8peYrWflbZ5lel4jabmZypPYZIkmiJ2IwUJYCHU61hco/ZDBFX30W0caqGZJ250=,iv:x+mBsMecDOSqwGDpMffEWgol631QM0pAphlamvzVD58=,tag:qItHfFt//Yexap4PHDY5Gw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: democratic-csi-nfs-values
    namespace: democratic-csi
sops:
    age:
        - recipient: age1xslhlhf7u3xy5pvrz4anpc0cltmuxgm8whm9686dpssqg86vv52s47wyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eHhVTFpuZENEUkZmTjZh
            bzdGYWZqTVNnbU9Pa01HV1grK3NDQ1BndVQ4CnlON004TCtTRzBpbmdDVXl6cmQw
            VTgrZ1J6QVVMSjBUclhrQklENGhaK3MKLS0tIGxwc3U5M1pra29tZ2t3bGd4dmhw
            SWFoTVVkck1aaGJ1QXlhWWpTdEFLTkkKUgprUI35sM3Q/C2NHqUrFbU+9p+D3UXn
            4D0lvbya3R8B3/+cXt7kX83TbgaXFvlCGFytOyuZlILGcnly6cUeOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T20:35:31Z"
    mac: ENC[AES256_GCM,data:AY2yg75IEbUqBl4FwvFCTJgrGvCh8A+FB+t9Rv7SyrpE8AnyKGAN6ShpNnV25S9b7NiO6PnrJ6cA4sK605jfwxkoriNqWJ5X1NRvovYePSs/gZ7q8/WVtlhj8t0gPPPcCtXKBDC8JoO2Ubauph5Fc9pIQHyxkLv/q5PjYy5P1Xw=,iv:sTQaURKof5yWyaffUfnfGYWiZ7Op9XjX263TDFZxWGc=,tag:sp2wpVijRhcHjvaAop4mXQ==,type:str]
    encrypted_regex: ^(data|stringData|bundle)$
    version: 3.10.0
