#
#
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 10-talos-cluster-resources
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 01-cluster-prereqs
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/kubernetes/clusters/room101-a7d-prod1
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
      - kind: Secret
        name: cluster-vars-secret
        optional: false
