#
# create prereqs for cloud controller manager
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 30-ccm-configs
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 21-cni
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/early-bootstrap/cloud-controller-manager/configs/room101-a7d-prod1
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  kubeConfig:
    secretRef:
      name: room101-a7d-prod1-kubeconfig
---
#
# install cloud controller manager
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 31-ccm
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 30-ccm-configs
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/early-bootstrap/cloud-controller-manager
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  patches:
    - path: patches/helmrelease-remote-install.yaml
      target:
        kind: HelmRelease
    - path: patches/helmrepository-cluster-namespace.yaml
      target:
        kind: HelmRepository
    - patch: |
        - op: replace
          path: /metadata/name
          value: proxmox-cloud-controller-manager-room101-a7d-prod1
        - op: replace
          path: /spec/releaseName
          value: proxmox-cloud-controller-manager-room101-a7d-prod1
      target:
        kind: HelmRelease
        name: proxmox-cloud-controller-manager
    #
    # kubelet-csr-approver
    #
    - patch: |
        - op: replace
          path: /metadata/name
          value: kubelet-csr-approver-room101-a7d-prod1
        - op: replace
          path: /spec/releaseName
          value: kubelet-csr-approver-room101-a7d-prod1
        - op: add
          path: /spec/values/providerIpPrefixes
          value:
            - 172.25.101.0/27
        - op: add
          path: /spec/values/providerRegex
          value: "^room101-[a-z0-9]+-prod1-(workers|cp)-[a-z0-9]+-[a-z0-9]+$"
      target:
        kind: HelmRelease
        name: kubelet-csr-approver
