---
#
# install addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 40-addons-pre-setup
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 31-ccm
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/cluster-type/capi-cluster/pre-setup
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
      - kind: Secret
        name: cluster-vars-secret
        optional: false
  kubeConfig:
    secretRef:
      name: room101-a7d-prod1-kubeconfig
---
#
# pre-setup config per cluster
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 41-addons-pre-setup-config
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 31-ccm
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/clusters/room101-a7d-prod1
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
---
#
# install MC addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 42-addons
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 40-addons-pre-setup
      namespace: cluster-room101-a7d-prod1
    - name: 41-addons-pre-setup-config
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/cluster-type/capi-cluster
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
      - kind: Secret
        name: cluster-vars-secret
        optional: false
  patches:
    # ensure helmreleases are reconciled locally against remote MC
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: "*"
        spec:
          kubeConfig:
            secretRef:
              name: room101-a7d-prod1-kubeconfig
          chart:
            spec:
              sourceRef:
                namespace: cluster-room101-a7d-prod1
      target:
        kind: HelmRelease
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-prod1
      target:
        kind: HelmRelease
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-prod1
      target:
        kind: HelmRepository
    #
    # cert-manager
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=cert-manager
          # url=https://charts.jetstack.io
          value: 1.18.2
      target:
        kind: HelmRelease
        name: cert-manager
    #
    # democratic-csi
    #
    # ensure correct value substitutions for prod1
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: democratic-csi-nfs
        spec:
          valuesFrom:
            - kind: ConfigMap
              name: democratic-csi-prod1-nfs-values
              optional: false
              valuesKey: values.yaml
            - kind: Secret
              name: democratic-csi-prod1-nfs-values
              optional: false
              valuesKey: values.yaml
      target:
        kind: HelmRelease
        name: democratic-csi-nfs
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=democratic-csi
          # url=https://democratic-csi.github.io/charts/
          value: 0.15.0
      target:
        kind: HelmRelease
        name: democratic-csi-nfs
    #
    # external-dns
    #
    - patch: |
        - op: add
          path: /spec/values/txtOwnerId
          value: "room101a7prod1"
        - op: add
          path: /spec/values/sources
          value:
            - crd
            - ingress
        - op: add
          path: /spec/values/crd
          value:
            create: true
            apiversion: "externaldns.k8s.io/v1alpha1" # CHECKME
            kind: "DNSEndpoint"
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=docker
          # chartname=external-dns
          # url=oci://registry-1.docker.io/bitnamicharts
          value: 8.9.2
      target:
        kind: HelmRelease
        name: external-dns
    #
    # kyverno
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=kyverno
          # url=https://kyverno.github.io/kyverno/
          value: 3.4.4
      target:
        kind: HelmRelease
        name: kyverno
    #
    # nginx
    #
    - patch: |
        - op: add
          path: /spec/values/controller/service/loadBalancerIP
          value: "${NGINX_SVC_IP}"
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=ingress-nginx
          # url=https://kubernetes.github.io/ingress-nginx
          value: 4.13.0
      target:
        kind: HelmRelease
        name: ingress-nginx
---
#
# create configs which depend on controllers which were installed by the prior kustomization
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 43-addons-post-setup
  namespace: cluster-room101-a7d-prod1
spec:
  dependsOn:
    - name: 42-addons
      namespace: cluster-room101-a7d-prod1
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/workloads/addons/config/post/room101-a7d-prod1
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-admission-controller
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-background-controller
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  kubeConfig:
    secretRef:
      name: room101-a7d-prod1-kubeconfig
