#
# pre-setup for addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 60-apps-pre-setup
  namespace: cluster-room101-a7d-prod1
spec:
  interval: 10m0s
  dependsOn:
    - name: 50-cluster-configs
      namespace: cluster-room101-a7d-prod1
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-prod1/pre-setup
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  kubeConfig:
    secretRef:
      name: room101-a7d-prod1-kubeconfig
---
#
# install addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 61-apps
  namespace: cluster-room101-a7d-prod1
spec:
  interval: 10m0s
  dependsOn:
    - name: 60-apps-pre-setup
      namespace: cluster-room101-a7d-prod1
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-prod1
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  patches:
    #
    # ensure helmreleases are reconciled locally against remote MC
    #
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: "*"
        spec:
          kubeConfig:
            secretRef:
              name: room101-a7d-prod1-kubeconfig
          chart:
            spec:
              sourceRef:
                namespace: cluster-room101-a7d-prod1
      target:
        kind: HelmRelease
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-prod1
      target:
        kind: HelmRelease
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-prod1
      target:
        kind: HelmRepository
    #
    # pinnpied-concierge
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=pinniped
          # url=oci://registry-1.docker.io/bitnamicharts
          value: 2.4.20
      target:
        kind: HelmRelease
        name: pinniped-concierge
    #
    # pinniped-supervisor
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=pinniped
          # url=oci://registry-1.docker.io/bitnamicharts
          value: 2.4.20
      target:
        kind: HelmRelease
        name: pinniped-supervisor
    #
    # oauth2-proxy-a7d-dev
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=oauth2-proxy
          # url=https://oauth2-proxy.github.io/manifests
          value: 6.24.2
      target:
        kind: HelmRelease
        name: oauth2-proxy-a7d-dev
    #
    # oauth2-proxy-analbeard-com
    #
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          # renovate: datasource=helm
          # chartname=oauth2-proxy
          # url=https://oauth2-proxy.github.io/manifests
          value: 6.24.2
      target:
        kind: HelmRelease
        name: oauth2-proxy-analbeard-com

        
        
---
#
# post-setup for addons
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 62-apps-post-setup
  namespace: cluster-room101-a7d-prod1
spec:
  interval: 10m0s
  dependsOn:
    - name: 61-apps
      namespace: cluster-room101-a7d-prod1
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/room101-a7d-prod1/post-setup
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: false
  kubeConfig:
    secretRef:
      name: room101-a7d-prod1-kubeconfig
