apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      version: ">=v3.0.0 < v4.0.0"
  interval: 60m
  storageNamespace: kyverno
  targetNamespace: kyverno
  install:
    remediation:
      retries: 3
