apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: cluster-room101-a7d-mc
data:
  CLUSTER: "room101-a7d-mc"
  WORKER_COUNT: "3"
  MASTER_COUNT: "3"
  K8S_VERSION: "1.28.3"
  TALOS_VERSION: "v1.5.5"
