apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-vars-configmap.yaml
  - server-master-203e63cb-a8aa-4bf8-a5b6-333090507777.yaml
  - server-master-2d1e5620-fdbc-4487-8f43-98cc9f36c308.yaml
  - server-master-7eb6cf89-d07f-40a5-bfb0-c3003045e013.yaml
  - serverclass-master.yaml
  - serverclass-worker.yaml
  - talos-secrets.yaml
