apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    cluster: room101-a7d-mc
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: override
  name: 7eb6cf89-d07f-40a5-bfb0-c3003045e013
spec:
  accepted: false
  hostname: 7eb6cf89-d07f-40a5-bfb0-c3003045e013
  configPatches:
  - op: replace
    path: /machine/network/interfaces
    value:
      - interface: eth0
        dhcp: false
        addresses:
          - 172.25.100.3/27
