apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    cluster: room101-a7d-mc
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: fc25565c-e70d-4e6f-9e60-bf966ea330f3
spec:
  accepted: true
  hostname: fc25565c-e70d-4e6f-9e60-bf966ea330f3
  configPatches:
  - op: replace
    path: /machine/network/interfaces
    value:
      - interface: eth0
        dhcp: true
