apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: room101-a7d-mc-worker
spec:
  selector:
    matchLabels:
      metal.sidero.dev/cluster: room101-a7d-mc
      metal.sidero.dev/machine.type: worker
  qualifiers:
    hardware:
    - system:
        skuNumber: worker
  configPatches:
  - op: add
    path: /machine/features/kubePrism
    value:
      enabled: true
      port: 6543
  - op: replace
    path: /machine/kubelet/extraArgs
    value:
      rotate-server-certificates: true
  - op: replace
    path: /machine/network/nameservers
    value:
      - 10.101.0.2
      - 10.101.0.3
  - op: replace
    path: /machine/install/disk
    value: /dev/vda
  - op: replace
    path: /machine/install/extensions
    value:
      - image: ghcr.io/siderolabs/qemu-guest-agent:8.0.2
  - op: replace
    path: /cluster/controlPlane/endpoint
    value: "https://k8s.room101-a7d-mc.lab.a7d.dev:6443"
  - op: replace
    path: /cluster/network/cni
    value:
      name: "none"
  - op: replace
    path: /cluster/apiServer/certSANs
    value:
      - k8s.room101-a7d-mc.lab.a7d.dev
  - op: replace
    path: /cluster/proxy/disabled
    value: true
