apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    cluster: room101-a7d-mc
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: 6904e125-fc6c-4614-a16f-bef7474373f4
spec:
  accepted: true
  configPatches:
  - op: replace
    path: /machine/network/interfaces
    value:
      - interface: eth0
        dhcp: true
