apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 40-controllers-cluster-api-operator-sidero-prereqs
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 30-addons
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/room101-a7d-mc/sidero-prereqs
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 41-controllers-cluster-api-operator
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 40-controllers-cluster-api-operator-sidero-prereqs
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./workloads/controllers/management-cluster/cluster-api-operator
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 42-controllers-capi-providers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 41-controllers-cluster-api-operator
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./workloads/controllers/management-cluster/cluster-api-operator/capi-providers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
