apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 40-controllers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 30-addons
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./workloads/controllers/management-cluster
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 41-controllers-infrastructure-provider-prereqs
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 40-controllers
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/room101-a7d-mc/sidero-prereqs
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 42-controllers-capi-providers
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: 41-controllers-infrastructure-provider-prereqs
      namespace: cluster-room101-a7d-mc
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./workloads/controllers/base/cluster-api-operator/capi-providers
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
  patches:
    - patch: |
        - op: add
          path: /spec
          value:
            version: v0.6.2
      target:
        kind: BootstrapProvider
        name: talos # https://github.com/siderolabs/cluster-api-bootstrap-provider-talos
    - patch: |
        - op: add
          path: /spec
          value:
            version: v0.5.3
      target:
        kind: ControlPlaneProvider
        name: talos # https://github.com/siderolabs/cluster-api-control-plane-provider-talos
    - patch: |
        - op: add
          path: /spec
          value:
            version: v1.5.3
      target:
        kind: CoreProvider
        name: cluster-api # https://github.com/kubernetes-sigs/cluster-api
    - patch: |
        - op: add
          path: /spec/version
          value: v0.6.1
      target:
        kind: InfrastructureProvider
        name: sidero # https://github.com/siderolabs/sidero
