apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 60-apps
  namespace: cluster-room101-a7d-mc
spec:
  interval: 10m0s
  dependsOn:
    - name: 60-cluster-configs
      namespace: cluster-room101-a7d-mc
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/room101-a7d-mc
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: true
