apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-flux-prereqs
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: inf-cni
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/flux/prereqs
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-flux-configs
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: inf-flux-prereqs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/room101-a7d-mc/flux-configs
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inf-flux
  namespace: cluster-room101-a7d-mc
spec:
  dependsOn:
    - name: cluster-prereqs
    - name: inf-flux-configs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/flux
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-mc
      target:
        kind: HelmRepository
        name: fluxcd-community
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-mc
        - op: add
          path: /spec/storageNamespace
          value: flux-system
        - op: add
          path: /spec/targetNamespace
          value: flux-system
        - op: add
          path: /spec/values/kustomization/path
          value: "./clusters/room101-a7d-mc"
      target:
        kind: HelmRelease
        name: flux-sync
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cluster-room101-a7d-mc
        - op: add
          path: /spec/storageNamespace
          value: flux-system
        - op: add
          path: /spec/targetNamespace
          value: flux-system
      target:
        kind: HelmRelease
        name: flux
  suspend: true
