apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps.yaml
- infrastructure-cni.yaml
- infrastructure-configs.yaml
- infrastructure-controllers.yaml
- infrastructure-flux.yaml
