apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: cluster-room101-a7d-mc
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-sync
    namespace: flux-system
  path: ./clusters/bootstrap/test
  prune: true
