apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex-k8s-authenticator
  namespace: dex
spec:
  values:
    config:
      clusters:
        - name: room101-a7d-mc
          k8s_ca_pem: |
            -----BEGIN CERTIFICATE-----
            MIIBizCCATCgAwIBAgIRAKxQFe9XATS7RuUgLDncm0gwCgYIKoZIzj0EAwIwFTET
            MBEGA1UEChMKa3ViZXJuZXRlczAeFw0yMzEyMTExNzEwMjZaFw0zMzEyMDgxNzEw
            MjZaMBUxEzARBgNVBAoTCmt1YmVybmV0ZXMwWTATBgcqhkjOPQIBBggqhkjOPQMB
            BwNCAARa9GZlE8KeQITeDovUJQRSSaaWUA+TaJigPMecJtuucBJLKvHBgZlYiuq8
            d0u324IkoKVKF6elxA2z5ndKiwA3o2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0l
            BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
            BBYEFLpoK052uIGQbrM5PHm1dCc5hO01MAoGCCqGSM49BAMCA0kAMEYCIQCdmJFj
            gmJ9/jlTTsp/+zn7aouZL9ZqZdd3faPuQ/ayfgIhAO6X8D8hvp6zs+2bZfZqSvFI
            VPLJUj/tSKwS+rmQ3Zd4
            -----END CERTIFICATE-----

