apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/dex
patches:
- path: dex-secret-dex-config.yaml
- path: dex-secret-dex-github-secret.yaml
- path: dex-secret-dex-k8s-authenticator-credentials.yaml
- path: patches/dex-k8s-authenticator-k8s-ca.yaml
  target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: dex-k8s-authenticator