apiVersion: v1
kind: Secret
metadata:
    name: sidero-config
    namespace: sidero-system
stringData:
    SIDERO_CONTROLLER_MANAGER_API_ENDPOINT: ENC[AES256_GCM,data:u9lXljIcwTUSyktDvUYwIAgL771qDp6OCyEWN07BbK1M,iv:SGhZfhhN4CZ+jgEupKEVOMovlgyZQ0wmZ9rkr7pnd3o=,tag:6MKiTDCsYN9P2Mk968a33Q==,type:str]
    SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT: ENC[AES256_GCM,data:tzRndTf9ITADmAZThvlcnXTV8S1+tgPruVmsf+EDBXUf,iv:caQfZBeQa5bt07bXTmj7UpHdO7LrThS1G/sBO9gQsSo=,tag:sAFzE0bKDX4ub5Y+izYWIg==,type:str]
    SIDERO_CONTROLLER_MANAGER_AUTO_BMC_SETUP: ENC[AES256_GCM,data:o5Byml0=,iv:6sk6pM9+2SIm4Vd3qIOfItDDm46R2QzC8vPxkq+TMlE=,tag:ux+O+moTILfX5AQHo6W4xg==,type:str]
    SIDERO_CONTROLLER_MANAGER_IPMI_PXE_METHOD: ENC[AES256_GCM,data:QmjTZg==,iv:TcvtjXQYIw64zEkadSjbqz2dLWV/m1ibyPLLAvHQITw=,tag:En9pzxEyUB3EviFijKsqlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xslhlhf7u3xy5pvrz4anpc0cltmuxgm8whm9686dpssqg86vv52s47wyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNGlkaUtsYzUyVlplbytO
            cVlNSFFqV0tSSFQyMWpIdVVuMXBiSmthSldRCjc4S0tLZjBuWmtCSUJqdWJjYitx
            Q29IRGNEZGFlSFViUS9CM05oTWxnNFUKLS0tIDM3SUhKSWpNcGFYdHIyd2lKa2Zl
            VDh1MjBlZ1loWHFNcjZQb3hEYlpBMncK1aZN5pLv/xwG3igwW0d8ge9/Ly8eSjjx
            gGJs/2uvS5H5xsHnH+QgA+Fv2sa21MGv0hzXr5puSdmxteGocSsObQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-21T21:00:25Z"
    mac: ENC[AES256_GCM,data:Z8TYvBUs2ivO0cQkRAxm+Sbivcjge131/WNjjhl5wsfDqSa9TcjmiJ/zrtRHQLKZ8u9vOTGGpoAsFvGZTbzp/UKZ9J9uwQK49BkfxMpGrny+7SwiXHykE+mhSaao9Bo5K7EYCeMWYeMKfjERc7ZhfJh5+oggAd9D7U3HCCe/G9o=,iv:st+hV/ql/9NTLMomYG4dz4e1HD2ibjewZTgEdm2u3ok=,tag:r8uAQkH5F0OG5jpZKbFNmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
