apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cluster-api-operator
  namespace: cluster-api-operator
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/cluster-api-operator
