apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-api-operator
  namespace: cluster-api-operator
spec:
  chart:
    spec:
      chart: cluster-api-operator
      sourceRef:
        kind: HelmRepository
        name: cluster-api-operator
      version: ">=0.5.0 <1.0.0"
  interval: 1m0s
  values:
    bootstrap: "talos"
    controlPlane: "talos"
    # infrastructure: "sidero" don't configure the infra provider as we set this manually in the cluster config dir
    secretName: "sidero-config"
    secretNamespace: "sidero-system"
