apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxmox-operator
  namespace: proxmox-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxmox-operator
  namespace: proxmox-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxmox-operator
subjects:
- kind: ServiceAccount
  name: proxmox-operator
  namespace: proxmox-operator
