apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  interval: 60m
  install:
    remediation:
      retries: 3
  storageNamespace: cert-manager
  targetNamespace: cert-manager
  values:
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers="10.96.0.10:53"
    installCRDs: true
