# https://github.com/ionos-cloud/cluster-api-provider-proxmox
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  namespace: proxmox-system
  name: proxmox
spec:
  configSecret:
    name: proxmox-provider-auth
    namespace: proxmox-system
  deployment:
    replicas: 1
