apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap-provider.yaml
  - controlplane-provider.yaml
  - core-provider.yaml
  - infrastructure-provider.yaml
  - ipam-provider.yaml
