- op: add
  path: /spec/controlPlaneConfig/controlplane/configPatches/0
  value:
    op: add
    path: /machine/features/kubernetesTalosAPIAccess
    value:
      enabled: true
      allowedRoles:
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system