apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/cluster-api-operator/releases/download/v0.6.0/operator-components.yaml
  - namespace-cabpt-system.yaml
  - namespace-cacppt-system.yaml
  - namespace-capi-system.yaml
  - namespace-sidero-system.yaml
patches:
  - path: patches/namespace-capi-operator-system.json
    target:
      version: v1
      kind: Namespace
      name: capi-operator-system
