apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/external-dns
namePrefix: "app-"
patches:
- path: external-dns-secrets.yaml
  target:
    kind: Secret
- path: external-dns-values.yaml
  target:
    kind: HelmRelease
