apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped-supervisor
  namespace: pinniped-system
spec:
  releaseName: pinniped-supervisor
  chart:
    spec:
      chart: pinniped
      sourceRef:
        kind: HelmRepository
        name: bitnami-pinniped
  interval: 10m0s
  values:
    global:
      imagePullSecrets:
        - docker-io-credentials
      security:
        allowInsecureImages: true
    image:
      registry: docker.io
      repository: getpinniped/pinniped-server
      tag: v0.42.0
    concierge:
      enabled: false
    supervisor:
      replicaCount: 2
      resourcesPreset: micro
      service:
        public:
          type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: nginx
        hostname: ${PINNIPED_SUPERVISOR_SUBDOMAIN}.${CLUSTER_FQDN}
        tls: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
          kubernetes.io/tls-acme: "true"
          external-dns.alpha.kubernetes.io/hostname: ${PINNIPED_SUPERVISOR_SUBDOMAIN}.${CLUSTER_FQDN}
          external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DNS_EXTERNAL_TARGET}
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
