apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: "worker-${WORKER4_UUID}"
  labels:
    qemu.xfix.org/uuid: "${WORKER4_UUID}"
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-03
  vmid: 418
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      mac: "56:66:cc:93:19:2f"
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - ${CLUSTER}
    - management-cluster
    - ${QEMU_WORKER_SKU}
  options:
    ostype: "l26"
    bios: "seabios"
    machine: "pc-i440fx-8.0"
    smbios1: "uuid=${WORKER4_UUID},sku=${QEMU_WORKER_SKU_B64},family=${QEMU_FAMILY_B64},base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
