apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: qemu-vm-7eb6cf89-d07f-40a5-bfb0-c3003045e013
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-01
  vmid: 410
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - room101-a7d-mc
    - management-cluster
    - control-plane
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=7eb6cf89-d07f-40a5-bfb0-c3003045e013,sku=Y29udHJvbHBsYW5lCg==,family=cm9vbTEwMWE3ZG1jCg==,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
