apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: master2-room101-a7d-mc
  labels:
    qemu.xfix.org/uuid: "${MASTER2_UUID}"
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-02
  vmid: 411
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      mac: "8a:39:fb:1d:10:bb"
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - room101-a7d-mc
    - management-cluster
    - control-plane
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=${MASTER2_UUID},sku=Y29udHJvbHBsYW5lCg==,family=cm9vbTEwMWE3ZG1jCg==,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
