apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: "master-${MASTER3_SHORT}"
  labels:
    qemu.xfix.org/uuid: "${MASTER3_UUID}"
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-01
  vmid: 412
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      mac: "88:5D:FF:EC:6B:62"
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - ${CLUSTER}
    - management-cluster
    - ${QEMU_MASTER_SKU}
  options:
    ostype: "l26"
    bios: "seabios"
    machine: "pc-i440fx-8.0"
    smbios1: "uuid=${MASTER3_UUID},sku=${QEMU_MASTER_SKU_B64},family=${QEMU_FAMILY_B64},base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
