apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: worker3-room101-a7d-mc
  labels:
    qemu.xfix.org/uuid: "${WORKER3_UUID}"
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-01
  vmid: 417
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      mac: "0e:68:df:5f:8d:26"
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - room101-a7d-mc
    - management-cluster
    - worker
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=${WORKER3_UUID},sku=Y29udHJvbHBsYW5lCg==,family=d29ya2VyCg==,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
