apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVMrZ0F3SUJBZ0lRVXAxNVNqUElWcWg4bVNxUzBuUXRaekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRE14TVRFM01URTFOVm9YRFRNMU1ETXdPVEUzTVRFMQpOVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCS2JuMW4vUGRYY0hnejJJMHE4RUd0Y0tocm5ML3Vrd0JMYVhVWW40RmpGK2QxN1pjczk1aHRwRDgwUTgKMUtjeExDV3JIaE13TjJnVmdqLzNOMHFJeDZ5allUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVV6OFhEYkJsNjlydEo0eVRrb29DdEQ2dzhZU013Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU9ZdjNrSVAKR1oxLzRTNHVJeGhWT3YyWVo0cldUVFVCSERiSUcwMU5CQWtBQWlFQTkvbUNiWjloSEpCeWJwd2JaMis3Y0crTgpIMkJOdHlLOFVPREZYVXgwQmhNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://k8s.room101-a7d-prod1.lab.a7d.dev:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
