apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-vars-configmap.yaml
  - cluster-vars-secret.yaml
  - configmap-cluster-info.yaml
  - secret-room101-a7d-prod1-kubeconfig.yaml
