apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:YHNj0bxSzrI/jSJ0MHceW6qvs5ghmG8ixIwm/U2Uxf23zfxRhY5vjvgstsd27RAocT48vHn5w1+urvzIzh+FMCWkFiQ5QT7hfbuMgB2AebT5eG1rGYiKZfO9WU0zUMy2aDnLr+m4fIFOUGkwkMAuRMS9nB1S6h8e7pN+ALYYRyt9PGB2quxpFO8x+FEB7lg5VFHq0O15sShgJFVAd2FkBi9btqriZ0PkjfZjN2wN34qCSkkK3lB29QLcb+pguxY4ahtCiJRrLO/tCagNIZb6urupmGH7PR5+MXMTTkGWZtYqsFIY+swXN7aYP3fJ8WOwocy119fE7q7lkFbitLaGcbMK3Vj9rWvKp82t9603yvkaOFU4xNwsC9pIl08PZm30yP3PmopLl/JI8xOZhNgyDiT4NXYpSDDjD9KpIJEDjlNoWqKkko5uuPfem7I8wNst4G9n8bXDoQ2nlQPVy2StH6DE2LvJmbY7EBaOQHx1DSGBdGD5mukqlHgNHUzPYzXmzmm33rHQ+Thbs+qZUtsngna900K28xLyEilPnrEP5hPnvfaJLw6sIGMrrqHY8FAydzMDwcblYTtMz2teKGdP1H5FxJs7hOgZPUvAKw+yyYpRN/8X4Vt1bqgxKphtQwj28eUUeJvAhu+qpGP65MfNMXn65F7QLqHRM1b+JXisZcMuWNMCAdfHwmhC+b7euktLky95qK1yZoyeaSQv2H3pyi6H3Z94LShdbtRqf1hHKTONdlVNiiqKGTm/APq15DpMFoIi4M6OHnd7al29SOSJj2pBEHkrXLchiEAC8W+UawkOQefg8O3EK6wMU+2nToHTQtpM+rxhRruZLsnw5bYuq8CuUtGeQSG7Pc6VrlMel8ONuuVb5HPan/LNxtq5rl92hbb9FpDzwJ4j6vXotJjVeKp1/vpyp+aolPbQ2mfTm63OR3gG59uI7K24CGJENfag/RrriuTc9AKYj7cO4AFvoTr4yHQm+yyRjv9XFCV1lHJqb3v6UnZO2Y1ajaxpCHAjJjPWYnIUNwTVaWwkGC1l/Ke75rTL6V4B9VjY57dhJaTFHjCgelvPsL2vxXa9dxKxgTiM4oXsIeCkzTB/V2UPQ3x+H0MumIH4gXv2addvzKYWef68Js7IYYVRPN1OO08hNV5Bu3vCOQUn1J4PwbSrF2kwqn46YfD0sJAeOclZFqKcgo1K2l9AKcnwItpbLY73yHS5qNonvTIuLbzJGfYCAm8DFrlErpom,iv:CwJOQS6alcvz0XgDDfJ3X3TdIN0HOY6yQHLscmb1B8c=,tag:bUmXHoXW3uEAq/bBkbz9vg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    labels:
        flux-patch-target: helmrelease-values-from
    name: democratic-csi-prod1-nfs-values
    namespace: cluster-room101-a7d-prod1
sops:
    age:
        - recipient: age1nzkeza3m8wvw8jvmngkqwlfps0cmuql745examekth74k4pdqplql4uwj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cDh6SDVuL25seG5Sb0RQ
            UXpKZ0dtdW1TcU95M0FRamlHaktVVzVGYUV3Cm9FY2kzL2c2K2ZWc1hBQmJYMGha
            UTcwUmxpdFZNcTZpQ3YvcWRybkVHZUUKLS0tIC9CNnFSNXdSc2g0UU9uMk5hYnps
            a2J2bnc1UEJpNzVIdW5MVHJacFhWRk0KHbofUme2ezuFvDDy9Mtu/s+l5RtEzk0b
            IOL1DbIHOOUTlx9COpF6mY7l6i9rv6E66WKkVZc7q1t3WC78V2XxUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T10:09:58Z"
    mac: ENC[AES256_GCM,data:QhBFyCDXpbrU5ObO3+Q3W0tHUVJYs1cZOhLvK5xFfb5byfI/DEFnIPPPedRNcjXHTWHosnYvPL59WURlXcyAHVCwaO5CvGvA5Hk84CPYdWmMAeEatjuS1Qi/ZBiYWSw2i6yMMAqikZeyk0NSFm4gqiUMTHxxarpKXcjTvDKb9D0=,iv:0xkwg0iZBqIvOhtGRCTkp0plMbkoVqST7Gk9FisGqVs=,tag:jeq8YGEwF4ssH+yqP8vosg==,type:str]
    encrypted_regex: ^(data|stringData|bundle)$
    version: 3.10.2
