apiVersion: v1
data:
    cloudflare_api_token: ENC[AES256_GCM,data:Gj7yPLwzcqubwdFMA0+0855dp4IEcLHP40UaVozpWFw96tdbeHgNll350IEFoCHI030+g3172ZzCviAlAI2G0sC6DIqq22BJKWM6ow==,iv:9OEBQa9a3KPgqF10fLYbh5JQezndl+LhGeTqLUAYrhI=,tag:PvaKnNpGF22Vqi6ve4563w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: external-dns-cf-auth
    namespace: external-dns
sops:
    age:
        - recipient: age1nzkeza3m8wvw8jvmngkqwlfps0cmuql745examekth74k4pdqplql4uwj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsclVtT3ZnQ213WU1LTWxn
            NUVYanBiRDZjaGpaTnc5bFNWOUVHUGtXMUR3CkRoaTgzWW1tUEJqdzRwallGQ3Jo
            dFJGaWxyQ3pUTjczdE03elBiZUVvcmcKLS0tIEd0Y3NUc3dWMDZVZkJ6MjFtV2lW
            dSthcEh3ajBJN2JrM1RaUGhDTkhyU0kKthg7k3kP0LLIQzNZrDYyIUY14NvZlfH5
            70Xmxj/fEnu8z6SD5T/oIArJn+kBN04CkZAVUKRpaze1VWHnWmnSHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T19:19:41Z"
    mac: ENC[AES256_GCM,data:poapL83Te/e3yO9M4vG7e9ybmK3pZeG9qdMZqBB0jXyWEOWWx+SL7ziS/IC5+mAd/vVXhPfuKx+/kQrkDrHK0dYJzICe1kUH9aiNDwyceIduZI1ch8tkI8c3LSCoJydpIDtE01Eb25ItiJ8c3OxcWF7N7nNZD0uyAFLWX1FMOZA=,iv:Dou4a5b3Jz3JTBeRD/HYpvBe1uu49KzBT8tACAU1zqU=,tag:wDjcYiZdm4dcmtrjNK0a0A==,type:str]
    encrypted_regex: ^(data|stringData|bundle)$
    version: 3.10.2
