apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/pinniped-concierge-yaml/post-setup
- ../../base/flux-operator/post-setup
- secret-homelab-clusters-addons-github-auth.yaml
- secret-sops-age-addons.yaml
