apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:mXu4AutfqwPvAsFfCkNclL4uliNkk4oOzQnioX7XpF3tW79MC522UOelqGQwfqD2qznEYB+58knDMQqPVbXuSJntSIcLZQIytqYfty2Pfw8DTXQtVW3y4sBor6y3rTiGJgTpisgQ85HfuG6i3EMOsQtH3v/GX9hiIyNC4UIhMcsOtUzMvoJkWuBVjZp2nlwbsJz/pFp6b7uBCSQc5TgXIsjEnXMxSYXUpY1BNbt25zH3kv7vJTVpGMa30yvUy+wYEYbn2ob+58NbKakUaHunaggy/ozKcK9KieFu/Fj7k4eCCYBZKXaYe1BVQZHpg/Mqp6VLx6uV+t+LnWto,iv:CPzCfSU6hNXnzfKTjocWNs1hI5U3/FJUxcBcyJnHiqA=,tag:ssd+db9qM9Pt3DQHzFqSsA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age-addons
    namespace: flux-system
sops:
    age:
        - recipient: age1nzkeza3m8wvw8jvmngkqwlfps0cmuql745examekth74k4pdqplql4uwj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bXpRb1draHRleUcyYnU5
            TkZQdmVGOWNGblRqWWlXRWZoZDFieWpnZ21ZCllLL1ArRitpSmZrWEVycjJIMGZT
            WC9USWkwaUFKeWpraWpHclREQ3lkYmMKLS0tIEtWUVZVczZoeE9tYTROY0lwLzRh
            NnA2L2hVbXRQNC9uTlZnOHQrcWc2MGcKAh5Kb9nz0GST3RqUtSZwaFCnWuRm6+UR
            8X3LKkch/xu1C9kBP/QWU3k/FwYy0wLqQg/fG5oJjPXivw+z4l+7Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-05T20:55:43Z"
    mac: ENC[AES256_GCM,data:Io2cgoderfXiIGBT1ZxRcIcP82F9lV3bFI8oqXFyjnZvJm78kgbVCGw08SQTECQn3JTblJTOCUiJf4uZcef/7c8vyQr1an/QIhCmUDiFpR1rcSS7+SZHDul5EEZpfpsC8it4NsU/gWC62auqPUJEMpJws0q64wRxD/hxQ7Bze7k=,iv:e94gf9CKoGDcipXkoia0wpr85tM2AaeoF3MPTpbSBMQ=,tag:rarge3max26VoiujakGBNQ==,type:str]
    encrypted_regex: ^(data|stringData|bundle)$
    version: 3.10.2
