apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-analbeard-com
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy-analbeard-com
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      version: ">=6.0.0 <7.0.0"
  interval: 5m0s
  values:
    metrics:
      servicemonitor:
        enabled: false
    replicaCount: 2
    config:
      cookieName: ${OAUTH2_PROXY_ANALBEARD_COOKIE_NAME}
      existingSecret: oauth2-proxy-analbeard-com-credentials
    extraArgs:
      cookie-domain: ${OAUTH2_PROXY_ANALBEARD_COOKIE_DOMAIN}
      github-org: ${OAUTH2_PROXY_ANALBEARD_GITHUB_ORG}
      provider: ${OAUTH2_PROXY_ANALBEARD_PROVIDER}
      redirect-url: "https://${OAUTH2_PROXY_SUBDOMAIN}.${OAUTH2_PROXY_ANALBEARD_DOMAIN/oauth2/callback"
