apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-a7d-dev
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy-a7d-dev
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      version: ">=6.0.0 <7.0.0"
  interval: 60m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    metrics:
      servicemonitor:
        enabled: false
    replicaCount: 2
    config:
      cookieName: ${OAUTH2_PROXY_A7D_COOKIE_NAME}
      existingSecret: oauth2-proxy-a7d-dev-credentials
    extraArgs:
      cookie-domain: ${OAUTH2_PROXY_A7D_COOKIE_DOMAIN}
      github-org: ${OAUTH2_PROXY_A7D_GITHUB_ORG}
      provider: ${OAUTH2_PROXY_A7D_PROVIDER}
      redirect-url: "https://${OAUTH2_PROXY_SUBDOMAIN}.${OAUTH2_PROXY_A7D_DOMAIN}/oauth2/callback"
