apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-a7d-dev
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy-a7d-dev
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  interval: 5m0s
  values:
    metrics:
      servicemonitor:
        enabled: false
    replicaCount: 2
