apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: roon101-supervisor-jwt-authenticator
spec:
  issuer: "https://${PINNIPED_SUPERVISOR_SUBDOMAIN}.${CLUSTER_FQDN}/${PINNIPED_FEDERATION_DOMAIN}"
  audience: ${CLUSTER}-${PINNIPED_AUDIENCE_SUFFIX}