- op: add
  path: /spec/controlPlaneConfig/controlplane/configPatches/0
  value:
    op: replace
    path: /machine/install/image
    value: factory.talos.dev/installer/${FACTORY_SCHEMATIC_ID}:${TALOS_VERSION}