apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - ConfigMap
    orderLast:
    - ClusterPolicy

resources:
- configmap-proxy-env-vars.yaml
- clusterpolicy-proxy-env-vars.yaml
