apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-imagepullsecret-docker-io
  annotations:
    policies.kyverno.io/title: Sync docker.io imagepullsecret
    policies.kyverno.io/subject: Secret
spec:
  rules:
  - name: sync-docker-io-imagepullsecret
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - "*"
    generate:
      apiVersion: v1
      kind: Secret
      name: docker-io-credentials
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: ${CLUSTER_NAMESPACE}
        name: docker-io-credentials
