apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-env-config
  namespace: kube-system
data:
  vars: |
    controlPlaneEndpoint: "k8s.room101-a7d-mc.lab.a7d.dev"
    clusterDomain: "cluster.local"
    podSubnet: "10.244.0.0/16"
    serviceSubnet: "10.96.0.0/12"
    proxyAddress: "http://10.101.0.55:3128"
