apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: changeme
  namespace: default
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/${TALOS_VERSION}/initramfs-amd64.xz
  kernel:
    args:
    - console=tty0
    - console=ttyS0
    - consoleblank=0
    - earlyprintk=ttyS0
    - ima_appraise=fix
    - ima_hash=sha512
    - ima_template=ima-ng
    - init_on_alloc=1
    - initrd=initramfs.xz
    - nvme_core.io_timeout=4294967295
    - printk.devkmsg=on
    - pti=on
    - slab_nomerge=
    - talos.platform=metal
    url: https://github.com/siderolabs/talos/releases/download/${TALOS_VERSION}/vmlinuz-amd64
