apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - machinedeployment.yaml
  - metalcluster.yaml
  - metalmachinetemplate.yaml
  - talosconfigtemplate.yaml
  - taloscontrolplane.yaml
