apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server-master1-room101-a7d-mc.yaml
  - server-worker1-room101-a7d-mc.yaml
  - server-worker2-room101-a7d-mc.yaml
  # disabled to reduce cluster size
  #- server-master2-room101-a7d-mc.yaml
  #- server-master3-room101-a7d-mc.yaml
  #- server-worker3-room101-a7d-mc.yaml
  - serverclass-master.yaml
  - serverclass-worker.yaml
  - talos-secrets.yaml
