apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # standard nodes
  - server-controlplane-203e63cb.yaml
  - server-controlplane-2d1e5620.yaml
  - server-controlplane-7eb6cf89.yaml
  - server-worker-461b9ad1.yaml
  - server-worker-498eeb6c.yaml
  # nodes enabled for cluster upgrade
  ##- server-worker-6904e125.yaml
  ##- server-worker-fc25565c.yaml
  - serverclass-controlplane.yaml
  - serverclass-worker.yaml
  - talos-secrets.yaml
