apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # standard nodes
  - server-203e63cb.yaml
  - server-461b9ad1.yaml
  - server-498eeb6c.yaml
  # nodes enabled for cluster upgrade
  - server-2d1e5620.yaml
  - server-6904e125.yaml
  - server-fc25565c.yaml
  # disabled to reduce cluster size
  #- server-7eb6cf89.yaml
  - serverclass-master.yaml
  - serverclass-worker.yaml
  - talos-secrets.yaml
