apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    metal.sidero.dev/cluster: room101-a7d-mc
    metal.sidero.dev/machine.type: worker
    kubernetes.a7d.dev/machine.group: batch2
  name: ${WORKER4_UUID}
spec:
  accepted: false
  hostname: ${WORKER4_UUID}
  configPatches:
  - op: add
    path: /machine/nodeLabels/topology.kubernetes.io~1zone
    value: ${WORKER4_HOST} # see corresponding per-serverclass labels
  - op: replace
    path: /machine/network/hostname
    value: ${WORKER4_UUID}
  - op: replace
    path: /machine/network/interfaces
    value:
      - deviceSelector:
          busPath: "0*" # match first NIC
        dhcp: true
