apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    metal.sidero.dev/cluster: room101-a7d-mc
    metal.sidero.dev/machine.type: controlplane
  name: ${CONTROLPLANE3_UUID}
spec:
  accepted: false
  hostname: ${CONTROLPLANE3_UUID}
  configPatches:
  - op: add
    path: /machine/nodeLabels/topology.kubernetes.io~1zone
    value: ${CONTROLPLANE3_HOST} # see corresponding per-serverclass labels
  - op: replace
    path: /machine/network/hostname
    value: ${CONTROLPLANE3_UUID}
  - op: replace
    path: /machine/network/interfaces
    value:
      - deviceSelector:
          busPath: "0*" # match first NIC
        dhcp: false
        addresses:
          - 172.25.100.5/27
        routes:
          - network: 0.0.0.0/0
            gateway: 172.25.100.1
            metric: 1024

