apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: room101-a7d-mc-controlplane
spec:
  environmentRef:
    name: room101-a7d-mc
    namespace: cluster-room101-a7d-mc
  selector:
    matchLabels:
      metal.sidero.dev/cluster: ${CLUSTER}
      metal.sidero.dev/machine.type: ${QEMU_CONTROLPLANE_SKU}
  qualifiers:
    hardware:
    - system:
        skuNumber: ${QEMU_CONTROLPLANE_SKU}
  configPatches:
  - op: add
    path: /machine/nodeLabels
    value:
      metal.sidero.dev/serverclass: ${QEMU_CONTROLPLANE_SKU}
  - op: add
    path: /machine/features/kubePrism
    value:
      enabled: false
      port: 6543
  - op: add
    path: /machine/features/kubernetesTalosAPIAccess
    value:
      enabled: true
      allowedRoles:
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system
  - op: replace
    path: /machine/kubelet/extraArgs
    value:
      cloud-provider: external
      rotate-server-certificates: true
  - op: replace
    path: /machine/network/nameservers
    value:
      - 10.101.0.2
      - 10.101.0.3
  - op: replace
    path: /machine/time
    value:
      servers:
        - 10.101.0.2
        - 10.101.0.3
      bootTimeout: 1m0s
  - op: replace
    path: /machine/install/disk
    value: /dev/vda
  - op: replace
    path: /machine/install/extensions
    value:
      - image: ghcr.io/siderolabs/qemu-guest-agent:8.0.2
  - op: replace
    path: /machine/install/wipe
    value: true
  - op: replace
    path: /cluster/clusterName
    value: ${CLUSTER}
  - op: replace
    path: /cluster/controlPlane/endpoint
    value: "https://k8s.room101-a7d-mc.lab.a7d.dev:6443"
  - op: add
    path: /cluster/network/cni
    value:
      name: "none"
  - op: replace
    path: /cluster/apiServer/extraArgs
    value:
      oidc-issuer-url: "https://dex.room101-a7d-mc.lab.a7d.dev"
      oidc-client-id: 9aba9b32-e761-4507-8445-cea11a6b15da
      oidc-username-claim: email
      oidc-groups-claim: groups
  - op: replace
    path: /cluster/apiServer/certSANs
    value:
      - k8s.room101-a7d-mc.lab.a7d.dev
  - op: add
    path: /cluster/proxy/disabled
    value: true
