apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: room101-a7d-mc-worker
spec:
  environmentRef:
    name: room101-a7d-mc
    namespace: cluster-room101-a7d-mc
  selector:
    matchLabels:
      metal.sidero.dev/cluster: ${CLUSTER}
      metal.sidero.dev/machine.type: ${QEMU_WORKER_SKU}
  qualifiers:
    hardware:
    - system:
        skuNumber: ${QEMU_WORKER_SKU}
  configPatches:
  - op: add
    path: /machine/nodeLabels
    value:
      metal.sidero.dev/serverclass: ${QEMU_WORKER_SKU}
      topology.kubernetes.io/region: ${PVE_CLUSTER_NAME} # see corresponding per-node labels
  - op: add
    path: /machine/features/kubePrism
    value:
      enabled: false
      port: 6543
  - op: replace
    path: /machine/kubelet/extraArgs
    value:
      cloud-provider: external
      rotate-server-certificates: true
  - op: replace
    path: /machine/network/nameservers
    value:
      - 10.101.0.2
      - 10.101.0.3
  - op: replace
    path: /machine/time
    value:
      servers:
        - 10.101.0.2
        - 10.101.0.3
      bootTimeout: 1m0s
  - op: replace
    path: /machine/install/disk
    value: /dev/vda
  - op: replace
    path: /machine/install/image
    value: factory.talos.dev/installer/${FACTORY_SCHEMATIC_ID}:${TALOS_VERSION}
  - op: replace
    path: /machine/install/wipe
    value: true
  - op: replace
    path: /cluster/controlPlane/endpoint
    value: "https://k8s.room101-a7d-mc.lab.a7d.dev:6443"
