apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pinniped-concierge

resources:
  # renovate vmware/pinniped
  - https://github.com/vmware/pinniped/releases/download/v0.41.0/install-pinniped-concierge.yaml
  - poddisruptionbudget.yaml
