apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-a7d-dev
  namespace: oauth2-proxy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "oauth2-proxy.room101-a7d-mc.lab.a7d.dev"
    external-dns.alpha.kubernetes.io/target: "ingress.lab.a7d.dev"
spec:
  rules:
  - host: oauth2-proxy.room101-a7d-mc.lab.a7d.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy-a7d-dev
            port:
              number: 80
  tls:
  - hosts:
    - oauth2-proxy.room101-a7d-mc.lab.a7d.dev
    secretName: oauth2-proxy-a7d-dev-tls
