apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/oauth2-proxy
patches:
- path: ingress-oauth2-proxy-a7d-dev.yaml
  target:
    kind: Ingress 
- path: ingress-oauth2-proxy-analbeard-com.yaml
  target:
    kind: Ingress
- path: oauth2-proxy-a7d-dev-values.yaml
  target:
    kind: HelmRelease
- path: oauth2-proxy-analbeard-com-values.yaml
  target:
    kind: HelmRelease
- path: secret-oauth2-proxy-a7d-dev-credentials.yaml
  target:
    kind: Secret
- path: secret-oauth2-proxy-analbeard-com-credentials.yaml
  target:
    kind: Secret
