apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-analbeard-com
  namespace: oauth2-proxy
spec:
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      version: ">=6.0.0 <7.0.0"
  interval: 1m0s
  values:
    config:
      cookieName: _oauth2_analbeard_com_room101_a7d_mc
      existingSecret: oauth2-proxy-analbeard-com-credentials
    extraArgs:
      cookie-domain: ".analbeard.com"
      github-org: "simonweald"
      provider: "github"
      redirect-url: "https://oauth2-proxy.room101-a7d-mc.lab.analbeard.com/oauth2/callback"
