apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:kkAlG4a+Z3cGet47mES7ErvDGBrskKB+Y92b2A==,iv:JWmvQPPcoEDwbsdJziYpszV+2rpbtGyRYw8QGzhi1vQ=,tag:nqNiXyHAHzDyoSIjk8nvgw==,type:str]
    client-secret: ENC[AES256_GCM,data:f+iXyLgeinX8NEe9r6R5nzAIwm6Kj4CPDx8Cw+jjGweb8B2SYZkDtSSi0x3rufPO7LEdrJpTGO8=,iv:bx5ccsEdBbXUJDnZAKU+GzTCW9pGvZd4TWeyLSZhgoU=,tag:/c/fCVl13CTPmmsxu5R+IQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:iPGM70Qe3rgim7u/9/QC+b037b2702OKmmWqOznUu18yLYznrctXeA==,iv:QX4cVRfdK6mZoeQx6qOjHxFVYkJSuVhdxSxVqqbWl70=,tag:GnyZ1IDolOLlnhlOyoqxQQ==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy-analbeard-com-credentials
    namespace: oauth2-proxy
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xslhlhf7u3xy5pvrz4anpc0cltmuxgm8whm9686dpssqg86vv52s47wyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMm9NdHNZNlJaL0FZUW5w
            N1loOEdqMURmSXhaMU9TUTJYMHlsRE16Um1vCk9KOXB4VFcyTDRVMTJidE03VS82
            L3RwckRoS2J6TC93d0JhL0N5bDNVaFUKLS0tIGc5VnRlSXZRUEJDQ05lYTR2Q3B0
            WGtScjR0VGpJR2l4ZlNJV2lDQ053NlEKHHTgB1fPXA0T7Q9Ob1Hu13o4vG9WOWI2
            0Gxh07e2YtQbm+CzPxn1t6MPg2q1xrg+cGL6T3Wn0H4vLxGnuoRwBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T20:02:29Z"
    mac: ENC[AES256_GCM,data:oaDgzzvY0vYEicrA1xlJ/YPUi3zyFVBfvCE/colU0zbF8fOzM8tegqOLdjmm5pXlHRSnwH3eWD7SHlPxdj8hw//wZokMpnaDyS8l5BKcxztlQxU+cMuzdMc12tmLsehmQ7sIMU0QLNHBWCRtexcTUdrq/StBzCRvFdO1XSfCKOA=,iv:XIe8ZLMo8Uv7ZWl7kaPIJ3CdHaw4c6qbwWKJqhDGyg0=,tag:+DKC2cQlyk3vUG8hgNw4rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
