apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: "controlplane-${CONTROLPLANE5_UUID}"
  labels:
    qemu.xfix.org/uuid: "${CONTROLPLANE5_UUID}"
    kubernetes.a7d.dev/machine.group: batch2
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: virt-lab
  node: host-02
  vmid: 414
  pool: room101-a7d-mc
  autostart: true
  autostop: true
  cpu:
    type: custom-talos-kvm64
    sockets: 1
    cores: 2
  memory:
    size: 3072
    balloon: 3072
  network:
    net0:
      mac: "86:be:d3:a7:8a:f2"
      model: virtio
      bridge: vmbr0
      tag: 1100
  disk:
    virtio0:
      storage: local-lvm
      size: 30G
  tags:
    - ${CLUSTER}
    - management-cluster
    - ${QEMU_CONTROLPLANE_SKU}
  options:
    ostype: "l26"
    bios: "seabios"
    machine: "pc-i440fx-8.0"
    smbios1: "uuid=${CONTROLPLANE5_UUID},sku=${QEMU_CONTROLPLANE_SKU_B64},family=${QEMU_FAMILY_B64},base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=virtio0;net0"
    onboot: 1
    kvm: 1
    agent: 1
    protection: 0
