apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped-concierge
  namespace: pinniped-concierge
spec:
  releaseName: pinniped-concierge
  chart:
    spec:
      chart: pinniped
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
      version: ">=2.0.0 <3.0.0"
  interval: 10m0s
  values:
    global:
      imagePullSecrets:
        - docker-io-credentials
    supervisor:
      enabled: false
    concierge:
      enabled: true
      resourcesPreset: micro
      impersonationProxy:
        externalEndpoint: concierge.room101-a7d-mc.lab.a7d.dev
        mode: enabled
        service:
          type: ClusterIP