kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1beta2
metadata:
  name: proxmox-csi-plugin
  namespace: kube-system
spec:
  interval: 5m0s
  type: "oci"
  url: oci://ghcr.io/sergelogvinov/charts
