apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
  namespace: proxmox-csi
spec:
  releaseName: proxmox-csi-plugin
  chart:
    spec:
      chart: proxmox-csi-plugin
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi-plugin
      version: ">=v0.5.0 < v1.0.0"
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    existingConfigSecret: "proxmox-csi-auth"
