apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:tuxRxbTnlW+MUZRzQnu2VgeHBpn8q5r5plWbmp/WBvZcaZ4T36Z4uinK2HaQHDhtAYOlQ/RB7JzTg6jodXZUdHJzOorIKhMHiufwPE/7OsXUgK06dhfun0PO6zejWBjbYBLSmDhM0wq4+Ym9D2I4RY7RbBAeImPy1e2UhgUvkR1idYK1luyotej/HEANR8jAv96V1Ni7bqBbuxsj/84OeErciae8CnbJD9X89wg0GEqVnNwUq7A7+CcADWDgq8UDF+ntgB327k2/1aqKdDRw6uEh07Jmstw+Jn0ySYFlzbXoGuvPK5bJhDnGv0eluKVp8nceoc9za0ly/ri+fXnfmUNG/mbEgqjyCKmS1TB5tH4WEmDhCJy6W8FejUQzPou06tl7VnkPG+u/I+T8fVVqPuauGux+RoykI7JmM7OGEp59NEDhTGSpUmpv5ZFJuCa5+a0rBAZxiGskClwtt07U5dHdWitfrjjtBO5uK0rV49XVCASwUshATVzsuzPwTvM0bo4/pejU+aSrKkktxcom7aF4JQqsXTse8HkJ5V4oCp1XjmewJ5Suig==,iv:skNQYOYWPujOdJNbhlYvv7iSj1hsm9yJ1BOshryKkXY=,tag:u19acPXrGPiGs0MPpSngKg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: proxmox-csi-auth
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xslhlhf7u3xy5pvrz4anpc0cltmuxgm8whm9686dpssqg86vv52s47wyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMFU3bVRYbDlCQmEvdFli
            aFkyWXpTcjNUYnZJYlZPVzZBbUU5R0xBYWhFCmwyeVUxd0dSUTZ6Y2hIa2JhRlJS
            WHlGaDIraUpDUUhIRGhYeFYwejk2MEEKLS0tIDVxYnM2cXQ1MmNEemlCSGNyc2xo
            RFRVY1c1UThxMlk2a0FkVUM3WHJPaXcKfGXPRnichRv2RLzVL+kO0A81wjUuzXe8
            9+xsl+gC2rOIpRO+X/5KUd0i93DB81CTfHu+LnQ74TBSraMnRm42Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T12:57:59Z"
    mac: ENC[AES256_GCM,data:I5L/f1pmWX9F/ADQbFBtuEdiBeMg7id3cWkY6oG0iAe4H+29ziZYPgz2U84L6ULP5Y70rdFPWQbxM3isF8nnCm3Z9IXcjq2hLr8UZ4xAnC9go/QKAo0qZq5Hv6kG0vB1UKovztUCJgkLbBCa+RoVJZjC4XH4CcMIySqpIqRTRBY=,iv:3ygmsinlR2ibyOywofPP2VYFfND6kGs3epAhC622d9A=,tag:0DH0Yyd3eaNG6yVSOs+A7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|bundle)$
    version: 3.8.1
