apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 60m
  storageNamespace: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - ingress-nginx
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - ingress-nginx
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - controller
              topologyKey: kubernetes.io/hostname
      extraArgs:
        enable-ssl-passthrough: true
      ingressClassResource:
        default: true
      minReadySeconds: 10
      replicaCount: 2
      service:
        labels:
          io.cilium/bgp-announce: "worker"
