apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-clusters-addons
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  # path is patched in by the reconciling kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-clusters-addons