apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    metal.sidero.dev/cluster: room101-a7d-mc
    metal.sidero.dev/machine.type: controlplane
    kubernetes.a7d.dev/machine.group: batch2
  name: ${CONTROLPLANE6_UUID}
spec:
  accepted: true
  hostname: ${CONTROLPLANE6_UUID}
  configPatches:
  - op: add
    path: /machine/nodeLabels/topology.kubernetes.io~1zone
    value: ${CONTROLPLANE6_HOST} # see corresponding per-serverclass labels
  - op: replace
    path: /machine/network/hostname
    value: ${CONTROLPLANE6_UUID}
  - op: replace
    path: /machine/network/interfaces
    value:
      - deviceSelector:
          busPath: "0*" # match first NIC
        dhcp: false
        dhcpOptions:
          ipv6: false
        addresses:
          - 172.25.100.8/27
        routes:
          - network: 0.0.0.0/0
            gateway: 172.25.100.1
            metric: 1024
