apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering-policy-worker
spec:
 nodeSelector:
   matchLabels:
     # only nodes with the following label will announce routes
     k8s.a7d.dev/serverclass: worker
 virtualRouters:
 - localASN: ${BGP_CLUSTER_AS}
   serviceSelector:
     matchExpressions:
       # services must have the following label to be announced
       - {key: "io.cilium/bgp-announce", operator: In, values: ['worker']}
   neighbors:
    - peerAddress: "${CILIUM_BGP_PEER}/32"
      peerASN: ${BGP_PEER_AS}
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
