apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  releaseName: flux-sync
  chart:
    spec:
      chart: flux2-sync
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
      version: ">=1.6.0 <2.0.0"
  interval: 10m0s
  values:
    gitRepository:
      spec:
        url: "ssh://git@github.com/a7d-corp/homelab-clusters-fleet"
        ref:
          branch: "main"
        secretRef:
          name: "flux-github-auth"
    kustomization:
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-age
