apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  releaseName: flux
  chart:
    spec:
      chart: flux2
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
      version: ">=2.9.0 <3.0.0"
  interval: 10m0s
  values:
    imageAutomationController:
      create: false
    imageReflectionController:
      create: false
