apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidero
    io.cilium/bgp-announce: "worker"
  name: sidero-siderolink-loadbalancer
  namespace: sidero-system
spec:
  type: LoadBalancer
  loadBalancerIP: ${SIDERO_SIDEROLINK_IP}
  ports:
  - port: 51821
    protocol: UDP
    targetPort: siderolink
  selector:
    app: sidero
    cluster.x-k8s.io/provider: sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    control-plane: sidero-controller-manager
