apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  labels:
    metal.sidero.dev/cluster: room101-a7d-mc
    metal.sidero.dev/machine.type: worker
  name: 461b9ad1-3ff0-4bef-8e1e-0dbfc1d8fa43
spec:
  accepted: true
  hostname: 461b9ad1-3ff0-4bef-8e1e-0dbfc1d8fa43
  configPatches:
  - op: replace
    path: /machine/network/hostname
    value: 461b9ad1-3ff0-4bef-8e1e-0dbfc1d8fa43
  - op: replace
    path: /machine/network/interfaces
    value:
      - deviceSelector:
          busPath: "0*" # match first NIC
        dhcp: true
