apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:7FWg70vueXJN1yF/Wl74BXJfNQpRPMnSSPznvA==,iv:mKUxpEoT/mTcJhORQh4ZbjNjIGbTsoWWsKKBpk0WL7g=,tag:1fRYeWGwiiK2RHGrItn7bw==,type:str]
    client-secret: ENC[AES256_GCM,data:YtffLKRJdB0XB0sH5hFtej8yQUx9WzFLaBLjIbJAIJLnOSMInpioPBTp8ljyggDRkVbwnhJL/EY=,iv:JN567bGj3g1ERh/0wGc9veAj0cziKTjg/r9K4dD/SI8=,tag:CRSjeA+mf82ezbBlZGz9SA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:+RtYJjE5yz2O2Ad+cs1y7UtqQcfNcSQ8oPQ1DB+VVmE3ZtaJOyBv9O9nIW4=,iv:TOjp5b5DNeyxOnzfQw26ci79kOB27EMuzuGXouJRO2M=,tag:gyId1pkiohvOjG4shmtIpw==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy-a7d-dev-credentials
    namespace: oauth2-proxy
sops:
    age:
        - recipient: age1nzkeza3m8wvw8jvmngkqwlfps0cmuql745examekth74k4pdqplql4uwj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR3FSemJ1MWRZZmtQZXV6
            ZytUVXc4a2VFY2gxeXNKdjNCYlBYdkQzMUJNCmpqZUVWcXUwY0NQc2k2Q0p5dDlO
            bzl2a3lzTWtXS2crMEVqaGFDQ2JwTDAKLS0tIE9ZZEQzc2swUG1QYWZub3R0eEMr
            ZHRENFpZNm0waWpXUmpRMDRiTzR3cUEKnxfxzSevr0jW04KUASlcuTgfTJyE7Mxu
            EJxOmh7dGfsGqgHxgCCl9l08xhRNpD6e/LeaoN9qdVQC5/1sXjW8ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T13:17:20Z"
    mac: ENC[AES256_GCM,data:JvZPc1RHmyC/hBT/TM35eTAL1sYBR6ufE6Nc/DhiZstc+VmicBiemOwz+Erk02bb6X+gtCz2EYBO/Q1x+ow9oaye3sxHlko8tMEB/9f5D8+4vbat6j/VLzpFkZNfRCNg8gSogLVWLBsAblGBjVP+JS/J2uKuWZsNnyNmWqI8ucM=,iv:3zq4RSwoBPgGjw0IVJW29RjDm86UWvWSc7zVz6ByUEQ=,tag:0mBLEsyMWeTKbCdbd063FQ==,type:str]
    encrypted_regex: ^(data|stringData|bundle)$
    version: 3.10.2
