# https://github.com/siderolabs/sidero
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  namespace: sidero-system
  name: sidero
spec:
  secretName: sidero-config
  deployment:
    replicas: 1
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    containers: []
